Pull Request try
cyanlove/wp-security-bp pull request #1
Opened 2019-02-14 20:37 UTC by uri-ustrell

### Pull Request try

- I challange you to comment and require some changes to keep this test alive!

2019-02-14 20:40 UTC, uri-ustrell commented
> ### Pull Request try
> * I challenge you to comment and require some changes to keep this test alive!

<iframe src="https://giphy.com/embed/ZVik7pBtu9dNS" width="480" height="268" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/life-interesting-footage-ZVik7pBtu9dNS">via GIPHY</a></p>

2019-02-14 22:16 UTC, jbaldrich commented
This code is bullshit 🤮

2019-02-14 22:33 UTC, uri-ustrell commented
> This code is bullshit 🤮

Nice to hear from you, as always!

and now, try to reference one specific line to change or refactor

2019-02-14 23:03 UTC, jbaldrich requested changes
Consider line 116 as this adds nothing to the plugin

2019-02-15 15:44 UTC, uri-ustrell commented on wpbp-security/README.txt
> -`<?php code(); // goes in backticks ?>`
Blah blah

2019-02-22 13:27 UTC, closed without merging